### ISSUE TITLE
Translation nodes are created as superadmin author instead of logged-in user

### ISSUE THREAD

**Issue by gijsstegehuis** [coding3d/Polyglot#3]
When creating translations nodes through Umbraco UI nodes are created as super admin author instead of logged-in user.

**Comment by coding3d** [comment]
Thanks for the feedback. This will be fixed soon.

**Comment by coding3d** [comment]
I've corrected the problem in version 2.08, which I've just published. Thanks again! If there are any more problems, let me know.

**Comment by gijsstegehuis** [comment]
Superb!
We'll keep you updated.
